### ISSUE TITLE
import in code example in documentation is wrong

### ISSUE THREAD

**Issue by muranyia** [adafruit/Adafruit_CircuitPython_24LC32#16]
In the [online docs](https://docs.circuitpython.org/projects/24lc32/en/latest/#usage-example) this part of the code doesn't work:
``` python
import adafruit_eeprom

i2c = board.I2C()
eeprom = adafruit_eeprom.EEPROM_I2C(i2c)
```
changing it like this makes it work:
``` python
import adafruit_24lc32

i2c = board.I2C()
eeprom = adafruit_24lc32.EEPROM_I2C(i2c)
```
(If documentation bugs are to be submitted elsewhere, please advise me. Thanks.)

**Comment by FoamyGuy** [comment]
Thanks for reporting. Are you interested in submitting a PR to change it?

**Comment by muranyia** [comment]
I'd love to, but the bug is not present here. Is there a separate repo where docs.circuitpython.org pulls from, or they haven't updated their content?

**Comment by FoamyGuy** [comment]
@muranyia I think it gets populated from the [README.rst](https://github.com/adafruit/Adafruit_CircuitPython_24LC32/blob/main/README.rst#usage-example) file in this repo. Updating it inside of that file should fix it on the docs page as well.
