### ISSUE TITLE
How to write data to eeprom

### ISSUE THREAD

**Issue by phamhuyvn** [adafruit/Adafruit_CircuitPython_24LC32#22]
I try assign eeprom[0:10] = some data. But it not be stored in eeprom, just in variable eeprom

**Comment by FoamyGuy** [comment]
Can you post the full code that you are running and the results that you are seeing? Add some print statements if there aren't already to show the value that are coming out of eeprom variable before and after device has reset after it being written.

**Comment by FoamyGuy** [comment]
Closing this for now. If you're still having any trouble please feel free to re-open and if you can include more details about your trial and outcome.
